#encoding: utf-8
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

source 'http://www.rubygems.org'

gem 'cocoapods', '1.8.4'
gem 'cocoapods-pod-merge', '0.0.4'
